strip_digit_suffix: false
blacklist_columns:
- nmap
- chromosome_alt
- seqlen
- Nmismatch
- nMismatch
- N_tot
- I_tot
- D_tot
- M_tot
- H_tot
- S_tot
- gene_type
- gene_name
- taxon_id
- LCA_mapping
- readtype_noTE
- readtype
- cigartype
- weight
- homer_DetailedAnnotation
- homer_NearestPromoterID
- homer_EntrezID
- homer_NearestUnigene
- homer_NearestRefseq
- homer_NearestEnsembl
- homer_GeneAlias
- homer_GeneDescription
quick_color_columns:
- alignment_signature
- homer_Annotation
- homer_GeneName
- homer_TE_class
padj_threshold: 0.05
log2fc_threshold: 0
default_color_column: homer_Annotation
default_point_size: 5
default_opacity: 0.7
default_tooltip_columns:
- homer_TE_family
- homer_GeneName
- alignment_signature
- homer_Annotation
- chromosome
x_min: -20
x_max: 20
max_legend_classes: 20
show_all_points: false
max_nonsignificant_points: 10000
host: 127.0.0.1
port: 8050
debug: false
